//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EFAppli12
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EmployeeDBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EmployeeDBContext object using the connection string found in the 'EmployeeDBContext' section of the application configuration file.
        /// </summary>
        public EmployeeDBContext() : base("name=EmployeeDBContext", "EmployeeDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmployeeDBContext object.
        /// </summary>
        public EmployeeDBContext(string connectionString) : base(connectionString, "EmployeeDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmployeeDBContext object.
        /// </summary>
        public EmployeeDBContext(EntityConnection connection) : base(connection, "EmployeeDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeeModel", Name="ContractEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContractEmployee : Employee
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContractEmployee object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ContractEmployee CreateContractEmployee(global::System.Int32 id)
        {
            ContractEmployee contractEmployee = new ContractEmployee();
            contractEmployee.ID = id;
            return contractEmployee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HourlyPay
        {
            get
            {
                return _HourlyPay;
            }
            set
            {
                OnHourlyPayChanging(value);
                ReportPropertyChanging("HourlyPay");
                _HourlyPay = StructuralObject.SetValidValue(value, "HourlyPay");
                ReportPropertyChanged("HourlyPay");
                OnHourlyPayChanged();
            }
        }
        private Nullable<global::System.Int32> _HourlyPay;
        partial void OnHourlyPayChanging(Nullable<global::System.Int32> value);
        partial void OnHourlyPayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HoursWorked
        {
            get
            {
                return _HoursWorked;
            }
            set
            {
                OnHoursWorkedChanging(value);
                ReportPropertyChanging("HoursWorked");
                _HoursWorked = StructuralObject.SetValidValue(value, "HoursWorked");
                ReportPropertyChanged("HoursWorked");
                OnHoursWorkedChanged();
            }
        }
        private Nullable<global::System.Int32> _HoursWorked;
        partial void OnHoursWorkedChanging(Nullable<global::System.Int32> value);
        partial void OnHoursWorkedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeeModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(PermanentEmployee))]
    [KnownTypeAttribute(typeof(ContractEmployee))]
    public abstract partial class Employee : EntityObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeeModel", Name="PermanentEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PermanentEmployee : Employee
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PermanentEmployee object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PermanentEmployee CreatePermanentEmployee(global::System.Int32 id)
        {
            PermanentEmployee permanentEmployee = new PermanentEmployee();
            permanentEmployee.ID = id;
            return permanentEmployee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AnuualSalary
        {
            get
            {
                return _AnuualSalary;
            }
            set
            {
                OnAnuualSalaryChanging(value);
                ReportPropertyChanging("AnuualSalary");
                _AnuualSalary = StructuralObject.SetValidValue(value, "AnuualSalary");
                ReportPropertyChanged("AnuualSalary");
                OnAnuualSalaryChanged();
            }
        }
        private Nullable<global::System.Int32> _AnuualSalary;
        partial void OnAnuualSalaryChanging(Nullable<global::System.Int32> value);
        partial void OnAnuualSalaryChanged();

        #endregion

    }

    #endregion

}
